apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-dev

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
      - name: nginx-dev
        image: nginx:1.8
        ports:
        - containerPort: 80
