apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-prod

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
      - name: nginx-prod
        image: nginx:1.7.9
        ports:
        - containerPort: 80
